/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package goldapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pranav
 */
public class goldApp extends javax.swing.JFrame {

    int id = 0;
    String sr = "", d = "", t = "", cnm = "", cpho = "", fgw = "", gw = "", lw = "", sw = "", pw = "", bw = "", gf = "", gc = "";
    boolean p = false, is_calculation_done = false;
    Connection c = null;
    double ct = 0.0;

    public void Con() {

        try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:goldAppDB.db");

            System.out.println("Opened database successfully");

        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        System.out.println("Operation done successfully");

    }

    /**
     * Creates new form goldApp
     */
    public goldApp() {
        initComponents();
        setTopData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrintPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ReportLable = new javax.swing.JLabel();
        dotLine = new javax.swing.JLabel();
        CnameLabel = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        CphoneLabel = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        FullGoldWeightLabel = new javax.swing.JLabel();
        fullGoldWeight = new javax.swing.JTextField();
        dotLine1 = new javax.swing.JLabel();
        GoldWeightLabel = new javax.swing.JLabel();
        GoldWeight = new javax.swing.JTextField();
        LabWeightLabel = new javax.swing.JLabel();
        LabWeight = new javax.swing.JTextField();
        SampleLabel = new javax.swing.JLabel();
        Sample = new javax.swing.JTextField();
        PureWeightLabel = new javax.swing.JLabel();
        PureWeight = new javax.swing.JTextField();
        BalanceWeightLabel = new javax.swing.JLabel();
        BalanceWeight = new javax.swing.JTextField();
        dotLine2 = new javax.swing.JLabel();
        FinessLabel = new javax.swing.JLabel();
        finess = new javax.swing.JTextField();
        GoldCaratLabel = new javax.swing.JLabel();
        GoldCarat = new javax.swing.JTextField();
        SrNOLabel = new javax.swing.JLabel();
        srNo = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        TimeLabel = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        LogoPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        BrandName = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JLabel();
        CopyRightLabel = new javax.swing.JLabel();
        savePrint = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        withWT = new javax.swing.JCheckBox();
        searchbtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setResizable(false);

        PrintPanel.setBackground(new java.awt.Color(254, 254, 254));
        PrintPanel.setForeground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        ReportLable.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ReportLable.setForeground(new java.awt.Color(1, 1, 1));
        ReportLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportLable.setText("Assigning Report");

        dotLine.setText("---------------------------------------------------------------------------------------------------------------------------");

        CnameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        CnameLabel.setText("Custome Name:");

        cname.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cname.setForeground(new java.awt.Color(4, 2, 2));

        CphoneLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        CphoneLabel.setText("Custome Phone:");

        cphone.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cphone.setForeground(new java.awt.Color(4, 2, 2));
        cphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cphoneFocusLost(evt);
            }
        });

        FullGoldWeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        FullGoldWeightLabel.setText("Full Gold Weight:");

        fullGoldWeight.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fullGoldWeight.setForeground(new java.awt.Color(4, 2, 2));
        fullGoldWeight.setText("0.0");
        fullGoldWeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fullGoldWeightFocusLost(evt);
            }
        });

        dotLine1.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        GoldWeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        GoldWeightLabel.setText("Gold Weight:");

        GoldWeight.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        GoldWeight.setForeground(new java.awt.Color(4, 2, 2));

        LabWeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LabWeightLabel.setText("Lab Weight:");

        LabWeight.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        LabWeight.setForeground(new java.awt.Color(4, 2, 2));

        SampleLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        SampleLabel.setText("Sample :");

        Sample.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Sample.setForeground(new java.awt.Color(4, 2, 2));

        PureWeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PureWeightLabel.setText("Pure Weight:");

        PureWeight.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        PureWeight.setForeground(new java.awt.Color(4, 2, 2));

        BalanceWeightLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BalanceWeightLabel.setText("Balance Weight:");

        BalanceWeight.setEditable(false);
        BalanceWeight.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BalanceWeight.setForeground(new java.awt.Color(4, 2, 2));

        dotLine2.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        FinessLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        FinessLabel.setText("Gold Finess :");

        finess.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        finess.setForeground(new java.awt.Color(4, 2, 2));

        GoldCaratLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        GoldCaratLabel.setText("Gold Carat :");

        GoldCarat.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        GoldCarat.setForeground(new java.awt.Color(4, 2, 2));

        SrNOLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        SrNOLabel.setText("Sr. No :");

        srNo.setEditable(false);
        srNo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        srNo.setForeground(new java.awt.Color(4, 2, 2));
        srNo.setHighlighter(null);

        DateLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        DateLabel.setText("Date:");

        date.setEditable(false);
        date.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(4, 2, 2));

        TimeLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        TimeLabel.setText("Time:");

        time.setEditable(false);
        time.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(4, 2, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dotLine, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(dotLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(dotLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CphoneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(FullGoldWeightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullGoldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BalanceWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BalanceWeight))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SampleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sample))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(GoldWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GoldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PureWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PureWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FinessLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finess, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoldCaratLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GoldCarat, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SrNOLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srNo)
                        .addGap(18, 18, 18)
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ReportLable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dotLine, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SrNOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(srNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CphoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FullGoldWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullGoldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dotLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoldWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PureWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PureWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dotLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoldCaratLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoldCarat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LogoPanel.setBackground(new java.awt.Color(1, 1, 1));
        LogoPanel.setAlignmentX(0.0F);
        LogoPanel.setAlignmentY(0.0F);

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldapp/final_logo.png"))); // NOI18N

        BrandName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        BrandName.setForeground(new java.awt.Color(254, 254, 254));
        BrandName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BrandName.setText("Royal Gold & Silver Testing");

        Address.setForeground(new java.awt.Color(254, 254, 254));
        Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address.setText("Gani Building, 1stFloor- no : 245(1)");

        Address1.setForeground(new java.awt.Color(254, 254, 254));
        Address1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address1.setText("New Bazaar, Near Ulaga School,");

        Address2.setForeground(new java.awt.Color(254, 254, 254));
        Address2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address2.setText(" Kadayanallur - 627751.");

        phoneNo.setForeground(new java.awt.Color(254, 254, 254));
        phoneNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNo.setText("Phone No : +91 9146705670");

        CopyRightLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        CopyRightLabel.setForeground(new java.awt.Color(254, 254, 254));
        CopyRightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CopyRightLabel.setText("@ 2021 Developed By Ganak Softech");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BrandName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Address1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Address2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(phoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CopyRightLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrandName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CopyRightLabel)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout PrintPanelLayout = new javax.swing.GroupLayout(PrintPanel);
        PrintPanel.setLayout(PrintPanelLayout);
        PrintPanelLayout.setHorizontalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintPanelLayout.createSequentialGroup()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PrintPanelLayout.setVerticalGroup(
            PrintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        savePrint.setBackground(new java.awt.Color(1, 1, 1));
        savePrint.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        savePrint.setForeground(new java.awt.Color(254, 254, 254));
        savePrint.setText("Save & Print");
        savePrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePrintMouseClicked(evt);
            }
        });
        savePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePrintActionPerformed(evt);
            }
        });

        calculate.setBackground(new java.awt.Color(1, 1, 1));
        calculate.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        calculate.setForeground(new java.awt.Color(254, 254, 254));
        calculate.setText("Calculate Fine");
        calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateMouseClicked(evt);
            }
        });

        withWT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        withWT.setText("With wt");

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search Receipt");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });

        refreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        refreshbtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshbtn.setText("Refresh");
        refreshbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(searchbtn)
                .addGap(52, 52, 52)
                .addComponent(withWT)
                .addGap(29, 29, 29)
                .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(savePrint)
                .addGap(96, 96, 96)
                .addComponent(refreshbtn)
                .addGap(39, 39, 39))
            .addComponent(PrintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PrintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(withWT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addComponent(savePrint))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void setTopData(){
     DateFormat d = new SimpleDateFormat("dd-MM-yyyy");
                Date dat = new Date();
                System.out.println(d.format(dat));
                date.setText(d.format(dat));

                // Get system time and set to time col
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                System.out.println(sdf.format(cal.getTime()));
                time.setText(sdf.format(cal.getTime()));
                
                 Con();
                PreparedStatement s;
                try {
                    s = c.prepareStatement("SELECT id FROM report ORDER BY id DESC LIMIT 1;");
                    ResultSet rs = s.executeQuery();

                    if (rs.next()) {
                        id = rs.getInt("id");

                    }
                    c.close();
                    System.out.println("id = " + id + 1);
                    sr = String.valueOf(String.format("%05d", id + 1));
                    srNo.setText(sr);
                    is_calculation_done = true;            
                } catch (SQLException ex) {
                    Logger.getLogger(goldApp.class.getName()).log(Level.SEVERE, null, ex);
                }
 }
    private void calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateMouseClicked
        if (!PureWeight.getText().isEmpty() && !LabWeight.getText().isEmpty() && !cname.getText().isEmpty() && !cphone.getText().isEmpty()) {
           if(CFG.isValidDecimal(GoldWeight.getText()) && CFG.isValidDecimal(LabWeight.getText()) && CFG.isValidDecimal(PureWeight.getText())){
            
                

                // Get and calculate for gold finess
                double pw1 = Double.parseDouble(PureWeight.getText());
                double lw1 = Double.parseDouble(LabWeight.getText());
                double gf1 = pw1 / lw1;
                double gf2 = 0.0, balwt = 0.0;
                gf2 = gf1 * 100;
                ct = gf2 * 24;
                ct = ct / 100;
                System.out.println(gf1);
                finess.setText(String.format("%.2f", gf2));
                GoldCarat.setText(String.format("%.2f", ct));
                GoldCarat.setEditable(false);
                BalanceWeight.setEditable(false);
                balwt = Double.parseDouble(GoldWeight.getText()) - Double.parseDouble(LabWeight.getText());

                BalanceWeight.setText(String.format("%.2f", balwt));
           }
           else{
               JOptionPane.showMessageDialog(jPanel1, "please enter valid weights");
           }
               
        } 
        else {
            JOptionPane.showMessageDialog(jPanel1, "please fill all the form");
        }

        is_calculation_done=true;
    }//GEN-LAST:event_calculateMouseClicked

    private void savePrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePrintMouseClicked
        // TODO add your handling code here:

        if (is_calculation_done) {
            Con();
            PreparedStatement s;
            try {

                PreparedStatement p = c.prepareStatement("insert into report (sr_no,date,time,cname,cphone,full_gold_weight,gold_weight,lab_weight,sample_weight,pure_weight,balance_weight,gold_finess,gold_carat) values ( ?,?,?,?,?,?,?,?,?,?,?,?,?)");
                p.setString(1, sr);
                p.setString(2, date.getText());
                p.setString(3, time.getText());
                p.setString(4, cname.getText());
                p.setString(5, cphone.getText());
                p.setString(6, fullGoldWeight.getText());
                p.setString(7, GoldWeight.getText());
                p.setString(8, LabWeight.getText());
                p.setString(9, Sample.getText());
                p.setString(10, PureWeight.getText());
                p.setString(11, BalanceWeight.getText());
                p.setString(12, finess.getText());
                p.setString(13, GoldCarat.getText());

                p.executeUpdate();
                c.close();

            } catch (SQLException ex) {
                System.err.println(ex.getClass().getName() + ": " + ex.getMessage());
                System.exit(0);
            }

            //CheckBox Working
            boolean x = withWT.isSelected();
            if (x) {
                Receipt r = new Receipt();
                r.setVisible(true);
                r.set(x);
                dispose();

            } else {
                Receipt r = new Receipt();
                r.setVisible(true);
                r.set(x);
                dispose();
            }

            dispose();
           
           
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Please calculate the finess first!");

        }

    }//GEN-LAST:event_savePrintMouseClicked

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        new List().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchbtnMouseClicked

    private void refreshbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshbtnMouseClicked
        cname.setText("");
        cphone.setText("");
        GoldWeight.setText("");
        LabWeight.setText("");
        Sample.setText("");
        PureWeight.setText("");
        BalanceWeight.setText("");
        finess.setText("");
        GoldCarat.setText("");
        is_calculation_done=false;
    }//GEN-LAST:event_refreshbtnMouseClicked

    private void cphoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cphoneFocusLost
        if(!CFG.isValidMobile(cphone.getText())){
            JOptionPane.showMessageDialog(jPanel1, "invalid contact number");
        }
    }//GEN-LAST:event_cphoneFocusLost

    private void fullGoldWeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullGoldWeightFocusLost
        if(!CFG.isValidDecimal(fullGoldWeight.getText())){
            JOptionPane.showMessageDialog(jPanel1, "invalid full gold weight");
        }
    }//GEN-LAST:event_fullGoldWeightFocusLost

    private void savePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goldApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goldApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goldApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goldApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        TableUsingJava tb = new TableUsingJava();
        tb.createTable();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new goldApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JTextField BalanceWeight;
    private javax.swing.JLabel BalanceWeightLabel;
    private javax.swing.JLabel BrandName;
    private javax.swing.JLabel CnameLabel;
    private javax.swing.JLabel CopyRightLabel;
    private javax.swing.JLabel CphoneLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel FinessLabel;
    private javax.swing.JLabel FullGoldWeightLabel;
    private javax.swing.JTextField GoldCarat;
    private javax.swing.JLabel GoldCaratLabel;
    private javax.swing.JTextField GoldWeight;
    private javax.swing.JLabel GoldWeightLabel;
    private javax.swing.JTextField LabWeight;
    private javax.swing.JLabel LabWeightLabel;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JPanel PrintPanel;
    private javax.swing.JTextField PureWeight;
    private javax.swing.JLabel PureWeightLabel;
    private javax.swing.JLabel ReportLable;
    private javax.swing.JTextField Sample;
    private javax.swing.JLabel SampleLabel;
    private javax.swing.JLabel SrNOLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dotLine;
    private javax.swing.JLabel dotLine1;
    private javax.swing.JLabel dotLine2;
    private javax.swing.JTextField finess;
    private javax.swing.JTextField fullGoldWeight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton savePrint;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField srNo;
    private javax.swing.JTextField time;
    private javax.swing.JCheckBox withWT;
    // End of variables declaration//GEN-END:variables
}
